openapi: 3.0.0
paths:
  /v1/results:
    post:
      operationId: 登録
      summary: ''
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResultRequest'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadStatuses'
        '400':
          description: ''
      tags:
        - リザルト
info:
  title: Salmon Stats NEXT WAVE API Documents
  description: ''
  contact: {}
tags: []
servers: []
components:
  schemas:
    PaginatedDto:
      type: object
      properties:
        total:
          type: integer
          description: 総数
        limit:
          type: integer
          description: 上限数
        offset:
          type: integer
          description: オフセット
      required:
        - total
        - limit
        - offset
    ResultRequest:
      type: object
      properties:
        results:
          type: array
          items:
            type: string
      required:
        - results
    UploadStatus:
      type: object
      properties:
        salmon_id:
          type: number
          description: リザルトID
        status:
          type: string
          enum:
            - created
            - updated
            - not allowed
      required:
        - salmon_id
        - status
    UploadStatuses:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/UploadStatus'
      required:
        - results
